### actor index
GET http://localhost:3000/actor_path 

### actor create
POST http://localhost:3000/actor_path.json
Content-Type: application/json

{
  "first_name": "test",
  "last_name": "test",
  "known_for": "test",
  "gender": "man",
  "age": 84,
  "movie_id": 14
}

### actor show
GET http://localhost:3000/actor_path/5

### actor update
PATCH http://localhost:3000/actor_path/8
Content-Type: application/json

{
  "gender": "man"
}

### actor destroy
DELETE http://localhost:3000/actor_path/6

### movies index
GET http://localhost:3000/movie_path

### movies create
POST http://localhost:3000/movie_path 
Content-Type: application/json

{
  "title": "Fitzcarraldo",
  "year": 1982,
  "plot": "Wild man tries to move a boat",
  "director": "Werner Herzog",
  "english": false
}

### movie show
GET http://localhost:3000/movie_path/1

### movie update
PATCH http://localhost:3000/movie_path/10
Content-Type: application/json

{
  "title": "Blue Velvet",
  "year": 1994,
  "plot": "it's really wild",
  "director": "David Lynch",
  "english": true
}

### movie destroy
DELETE http://localhost:3000/movie_path/5