### actor index
GET http://localhost:3000/actor_path.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Mjk1OTB9.nxYeIjn91xW7v4fMBBM_VnF96B1qhWlzn6nomBhFS1I

### actor create
POST http://localhost:3000/actor_path.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1Mjc1Nzh9.ZMzn55LvVuRUDaxlg2q9_8GMAqPSuYlkXk_f9guVkEs
Content-Type: application/json

{
  "first_name": "test",
  "last_name": "test",
  "known_for": "test",
  "gender": "man",
  "age": 84,
  "movie_id": 14
}

### actor show
GET http://localhost:3000/actor_path/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Mjk1OTB9.nxYeIjn91xW7v4fMBBM_VnF96B1qhWlzn6nomBhFS1I

### actor update
PATCH http://localhost:3000/actor_path/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1Mjc1Nzh9.ZMzn55LvVuRUDaxlg2q9_8GMAqPSuYlkXk_f9guVkEs
Content-Type: application/json

{
  "gender": "man"
}

### actor destroy
DELETE http://localhost:3000/actor_path/20
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1Mjc1Nzh9.ZMzn55LvVuRUDaxlg2q9_8GMAqPSuYlkXk_f9guVkEs




### movies index
GET http://localhost:3000/movie_path.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Mjk1OTB9.nxYeIjn91xW7v4fMBBM_VnF96B1qhWlzn6nomBhFS1I

### movies create
POST http://localhost:3000/movie_path
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1Mjc1Nzh9.ZMzn55LvVuRUDaxlg2q9_8GMAqPSuYlkXk_f9guVkEs 
Content-Type: application/json

{
  "title": "Fitzcarraldo",
  "year": 1982,
  "plot": "Wild man tries to move a boat",
  "director": "Werner Herzog",
  "english": false
}

### movie show
GET http://localhost:3000/movie_path/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1Mjc1Nzh9.ZMzn55LvVuRUDaxlg2q9_8GMAqPSuYlkXk_f9guVkEs

### movie update
PATCH http://localhost:3000/movie_path/10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1Mjc1Nzh9.ZMzn55LvVuRUDaxlg2q9_8GMAqPSuYlkXk_f9guVkEs
Content-Type: application/json

{
  "title": "Blue Velvet",
  "year": 1994,
  "plot": "it's really wild",
  "director": "David Lynch",
  "english": true
}

### movie destroy
DELETE http://localhost:3000/movie_path/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1Mjc1Nzh9.ZMzn55LvVuRUDaxlg2q9_8GMAqPSuYlkXk_f9guVkEs





### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "chauncey",
  "email": "chauncey@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "katie@email.com",
  "password": "password"
}